#!/usr/bin/python
# -*- coding: utf-8 -*-
from __future__ import (print_function, division, absolute_import, unicode_literals, )

print('check commit message')

import io
import re
import sys

with io.open(sys.argv[1], 'rt') as f:
    message_lines = filter(lambda x: x, [line.strip() for line in f.readlines() if not line.startswith('#')])
    if not message_lines:
        print('\033[91mINVALID: no content.\033[0m')
        sys.exit(1)
    message = message_lines[0]
    has_id = re.search(r'#\d+', message)
    if has_id:
        if message.split(' ')[0] in {'refs', 'fixes', 'closes', }:
            print(message)
            sys.exit(0)

print('\033[91mINVALID: no ticket id.\033[0m')
sys.exit(1)
